<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <RootNamespace>Packtastic.Avalonia</RootNamespace>
        <Version>0.0.1-alpha1</Version>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>Packtastic.Avalonia.Core</Title>
        <PackageProjectUrl>https://github.com/GamerVII-NET/Packtastic.Avalonia</PackageProjectUrl>
        <PackageIcon>packtastik.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Build" Version="17.12.6">
        <ExcludeAssets>runtime</ExcludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Build.Locator" Version="1.7.8" />
      <PackageReference Include="System.Text.Json" Version="9.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Packtastic.Avalonia.Interfaces\Packtastic.Avalonia.Interfaces.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Core\Factories\WindowsSystemBuilder.cs">
        <DependentUpon>OperationSystemBuilderFactory.cs</DependentUpon>
      </Compile>
      <Compile Update="Core\Factories\SystemBuilderBase.cs">
        <DependentUpon>OperationSystemBuilderFactory.cs</DependentUpon>
      </Compile>
      <Compile Update="Core\Factories\LinuxSystemBuilder.cs">
        <DependentUpon>OperationSystemBuilderFactory.cs</DependentUpon>
      </Compile>
      <Compile Update="Core\Factories\DebPacker.cs">
        <DependentUpon>OperationSystemPackerFactory.cs</DependentUpon>
      </Compile>
      <Compile Update="Core\Factories\MsiPacker.cs">
        <DependentUpon>OperationSystemPackerFactory.cs</DependentUpon>
      </Compile>
      <Compile Update="Core\Factories\ZipPacker.cs">
        <DependentUpon>OperationSystemPackerFactory.cs</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <None Update="Templates\Wix\file-component.xml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Templates\Wix\template.wxs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="packtastik.png">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
      </None>
    </ItemGroup>

</Project>
